#!/bin/bash

INPUT=$1

# Define a temp directory
WORKING_DIR="/data/shares/DVD"

# We're in the US, so we use NTSC
export VIDEO_FORMAT=NTSC

# Generate global variables
FILE=$(basename "${INPUT}")
NAME=${FILE%.*}
UPPER_NAME=$(echo ${NAME// /_} | awk '{print toupper($0)}')

# Figure out how many chapters to make
LENGTH=$(ffprobe -v error -select_streams v:0 -show_format "${INPUT}" | grep "duration" | awk -F'=' '{print $2}' | awk -F'.' '{print $1}')
INTERVAL=$(echo "${LENGTH} / 300" | bc)
LAST_CHAPTER=$(echo "${INTERVAL} * 300" | bc)
CHAPTERS=$(seq -s, 0 300 ${LAST_CHAPTER})

# Enter working dir
cd ${WORKING_DIR}

# Transcode the file to MPEG2
echo "-- Converting source file to MPEG2"
ffmpeg -i "${INPUT}" -target ntsc-dvd -aspect 4:3 -filter:v 'scale=-1:480,pad=1440:480:(ow-iw)/2:(oh-ih)/2' -ac 2 "${NAME}.mpg"

# Create the DVD file structure
dvdauthor -o "${NAME}" -t -c "${CHAPTERS}" -f "${NAME}.mpg"
dvdauthor -o "${NAME}" -T

# Create an ISO file
genisoimage -dvd-video -V ${UPPER_NAME} -o "${NAME}.iso" "${NAME}"
chown nobody:nogroup "${NAME}.iso"

# Clean up after ourselves
rm -rf "${NAME}.mpg"
rm -rf "${NAME}"
