#!/bin/bash

INPUT=$1

# Define a temp directory
WORKING_DIR="/data/shares/DVD"

# We're in the US, so we use NTSC
export VIDEO_FORMAT=NTSC

# Generate global variables
FILE=$(basename "${INPUT}")
NAME=${FILE%.*}
UPPER_NAME=$(echo ${NAME// /_} | awk '{print toupper($0)}')

# Enter working dir
cd ${WORKING_DIR}

# Transcode the file to MPEG2
echo "-- Converting source file to MPEG2"
ffmpeg -i "${INPUT}" -target ntsc-dvd -aspect 16:9 -filter:v 'scale=720:-1,pad=720:480:(ow-iw)/2:(oh-ih)/2' -ac 2 "${NAME}.mpg"

# Create the DVD file structure
dvdauthor -o "${NAME}" -x "${NAME}.xml"
dvdauthor -o "${NAME}" -T

# Create an ISO file
genisoimage -dvd-video -V ${UPPER_NAME} -o "${NAME}.iso" "${NAME}"
chown nobody:nogroup "${NAME}.iso"

# Clean up after ourselves
rm -rf "${NAME}.mpg"
rm -rf "${NAME}"
